esphome:
  name: ${name}
  comment: Everything Presence Lite
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True
  project:
    name: EverythingSmartTechnology.Everything Presence Lite
    version: "1.2.9"  # Updated to the latest version

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:

# OTA configuration for over-the-air updates
ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

# Define the http_request component
http_request:
  useragent: esphome/1.1
  timeout: 10s
  verify_ssl: false

# WiFi configuration (Add your WiFi settings here)
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  manual_ip:
    static_ip: 10.0.0.137
    gateway: 10.0.0.2
    subnet: 255.255.255.0

# I2C bus configuration
i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true

# Number for illuminance offset
number:
  - platform: template
    name: "Illuminance Offset"
    id: illuminance_offset_ui
    unit_of_measurement: "lx"
    min_value: -100
    max_value: 100
    step: 5
    mode: slider
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:brightness-5"
    entity_category: config
    on_value:
      - lambda: 'id(illuminance_sensor).update();'

# Define your sensors here
sensor:
  - platform: bh1750
    name: "Illuminance Sensor"
    id: illuminance_sensor
    i2c_id: bus_a
    address: 0x23
    update_interval: ${illuminance_update_interval}
    filters:
      - lambda: "return x + id(illuminance_offset_ui).state;"
      - clamp:
          min_value: 0

  - platform: bme280_i2c
    i2c_id: bus_a
    temperature:
      name: "Temperature"
      oversampling: 8x
      id: temperature_sensor
    pressure:
      name: "Pressure"
      oversampling: 2x
      id: pressure
    humidity:
      name: "Humidity"
      oversampling: 8x
      id: humidity
    address: 0x76
    update_interval: 120s

# Button to restart the ESP
button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

