esphome:
  name: ${name}
  comment: Everything Presence Lite
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True
  project: 
    name: EverythingSmartTechnology.Everything Presence Lite
    version: "1.2.3"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

http_request:

wifi:

improv_serial:

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true

light:
  - platform: status_led
    name: ESP32 LED
    pin: GPIO14
    internal: False
    restore_mode: ALWAYS_OFF

number:
  - platform: template
    name: "Illuminance Offset"
    id: illuminance_offset_ui
    unit_of_measurement: "lx"
    min_value: -100
    max_value: 100
    step: 5
    mode: slider
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:brightness-5"
    entity_category: config
    on_value:
      - lambda: 'id(illuminance_sensor).update();'

# Switch to control BME280 power
switch:
  - platform: gpio
    id: bme280_power
    pin:
      number: GPIO23  # Use a non-strapping pin
      mode: OUTPUT
      inverted: false
    restore_mode: ALWAYS_OFF

sensor:
  - platform: bh1750
    name: Illuminance
    id: illuminance_sensor
    i2c_id: bus_a
    address: 0x23
    update_interval: ${illuminance_update_interval}
    filters:
      - lambda: "return x + id(illuminance_offset_ui).state;"
      - clamp:
          min_value: 0
          
  - platform: bme280_i2c
    i2c_id: bus_a
    temperature:
      name: "Temperature"
      id: temperature_sensor
    pressure:
      name: "Pressure"
      id: pressure
    humidity:
      name: "Humidity"
      id: humidity
    address: 0x76
    update_interval: 5s  # Disable periodic updates since we control it manually

interval:
  - interval: 1min
    then:
      - switch.turn_on: 
          id: bme280_power  # Power on the sensor first
      - delay: 1s  # A small delay to ensure power is supplied
      - i2c.scan:  # Scan the I2C bus
      - delay: 30s  # Give the sensor time to stabilize
      - switch.turn_off: 
          id: bme280_power  # Power off after reading


button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
