esphome:
  name: cave-sensors
  friendly_name: cave-sensors
  name_add_mac_suffix: False
  project:
    name: EverythingSmartTechnology.Everything Presence Lite
    version: "1.2.3"
  on_boot:
    priority: -100
    then:
      - switch.turn_on: 
          id: bme280_power
      - delay: 5s
      - delay: 30s
      - switch.turn_off: 
          id: bme280_power

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# OTA configuration for over-the-air updates
ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

# Define the http_request component
http_request:
  useragent: esphome/1.1
  timeout: 10s
  verify_ssl: false

# I2C bus configuration
i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true

# Switch to control BME280 power
switch:
  - platform: gpio
    id: bme280_power
    pin:
      number: GPIO23
      mode: OUTPUT
      inverted: false
    restore_mode: ALWAYS_OFF
    friendly_name: "BME280 Power"

# Define your sensors here
sensor:
  - platform: bh1750
    name: "Illuminance"
    id: illuminance_sensor
    i2c_id: bu
