esp32:
  board: esp32dev
  framework:
    type: esp-idf

# OTA configuration for over-the-air updates
ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

# Define the http_request component
http_request:
  useragent: esphome/1.1
  timeout: 10s
  verify_ssl: false

# I2C bus configuration
i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true

# Switch to control BME280 power
switch:
  - platform: gpio
    id: bme280_power
    pin:
      number: GPIO23
      mode: OUTPUT
      inverted: false
    restore_mode: ALWAYS_OFF

# Define your sensors here
sensor:
  - platform: bh1750
    name: "Illuminance Sensor"
    id: illuminance_sensor
    i2c_id: bus_a
    address: 0x23
    update_interval: ${illuminance_update_interval}
    filters:
      - lambda: "return x + id(illuminance_offset_ui).state;"
      - clamp:
          min_value: 0
    friendly_name: "Illuminance"
          
  - platform: bme280_i2c
    i2c_id: bus_a
    temperature:
      name: "Temperature"
      id: temperature_sensor
      friendly_name: "Temperature"
    pressure:
      name: "Pressure"
      id: pressure
      friendly_name: "Pressure"
    humidity:
      name: "Humidity"
      id: humidity
      friendly_name: "Humidity"
    address: 0x76
    update_interval: 5s

# Interval for periodic tasks
interval:
  - interval: 1min
    then:
      - switch.turn_on: 
          id: bme280_power
      - delay: 10s
      - sensor.read: temperature_sensor
      - sensor.read: pressure
      - sensor.read: humidity
      - switch.turn_off: 
          id: bme280_power
